import { createAccount, createClient, generatePrivateKey } from "genlayer-js";
import { studioDevnet } from "genlayer-js/chains";

const contract=process.env.CONTRACT_ADDRESS?.trim(),raw=process.env.GENLAYER_PRIVATE_KEY?.trim().replace(/^['"]|['"]$/g,""),artifact=process.env.ARTIFACT_SOURCE?.trim(),method=process.env.METHOD_SOURCE?.trim(),reportA=process.env.REPORT_A?.trim(),reportB=process.env.REPORT_B?.trim();
if(!contract||!raw||!artifact||!method||!reportA||!reportB)throw new Error("CONTRACT_ADDRESS, GENLAYER_PRIVATE_KEY, ARTIFACT_SOURCE, METHOD_SOURCE, REPORT_A, and REPORT_B are required");
const keeper=setInterval(()=>{},60000),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),key=raw.startsWith("0x")?raw:`0x${raw}`;
const chain={...studioDevnet,id:61997,name:"GenLayer Studio Next",rpcUrls:{default:{http:["https://studio-next.genlayer.com/api"]}}};const ownerAccount=createAccount(key),reviewerA=createAccount(generatePrivateKey()),reviewerB=createAccount(generatePrivateKey());const owner=createClient({chain,account:ownerAccount}),labA=createClient({chain,account:reviewerA}),labB=createClient({chain,account:reviewerB});
const studyId=`replica-demo-${Date.now().toString(36)}`;console.log(`DEMO_STUDY=${studyId}`);console.log(`REVIEWER_A=${reviewerA.address}`);console.log(`REVIEWER_B=${reviewerB.address}`);
async function finalized(client,hash){for(let attempt=0;attempt<300;attempt++){const receipt=await client.getTransaction({hash}).catch(()=>null);const status=String(receipt?.statusName??receipt?.status??"PENDING").toUpperCase();if(status==="FINALIZED")return receipt;if(["UNDETERMINED","DECLINED","CANCELED","CANCELLED"].includes(status))throw new Error(`Transaction ended ${status}`);await sleep(3000)}throw new Error("Transaction timed out before FINALIZED")}
async function write(client,label,functionName,args,intelligent=false){const fees=await client.estimateTransactionFees({leaderTimeunitsAllocation:intelligent?500n:180n,validatorTimeunitsAllocation:intelligent?600n:360n});const hash=await client.writeContract({address:contract,functionName,args,fees});console.log(`${label}_TX=${hash}`);const receipt=await finalized(client,hash);const status=String(receipt.statusName??receipt.status??"unknown"),execution=String(receipt.txExecutionResultName??receipt.txExecutionResult??"unknown"),consensus=String(receipt.resultName??receipt.result_name??"unknown");console.log(`${label}_STATUS=${status};EXECUTION_RESULT=${execution};CONSENSUS=${consensus}`);if(status!=="FINALIZED"||execution!=="FINISHED_WITH_RETURN"||consensus==="MAJORITY_DISAGREE")throw new Error(`${label} failed`);return hash}
await owner.transfer({to:reviewerA.address,value:100000000000000000n});await owner.transfer({to:reviewerB.address,value:100000000000000000n});await sleep(8000);
const obsA={outcome:"SUPPORTS",artifact_quote:"Tested artifact: model-echo-42",method_quote:"Followed protocol: seed 17 in Python 3.13",environment_quote:"Environment: Windows 11, Python 3.13",result_quote:"Result: checksum 7ac9 was reproduced exactly"};
const obsB={outcome:"SUPPORTS",artifact_quote:"Tested artifact: model-echo-42",method_quote:"Followed protocol: seed 17 in Python 3.13",environment_quote:"Environment: Ubuntu 24.04, Python 3.13",result_quote:"Result: checksum 7ac9 was reproduced exactly"};
await write(owner,"OPEN_STUDY","open_study",[studyId,"Echo checksum replication","The model-echo-42 artifact produces checksum 7ac9 when protocol 42 is followed.",artifact,method,JSON.stringify([reviewerA.address,reviewerB.address]),2,Math.floor(Date.now()/1000)+86400],true);
await write(labA,"REPORT_A","submit_report",[studyId,reportA,JSON.stringify(obsA)],true);await write(labB,"REPORT_B","submit_report",[studyId,reportB,JSON.stringify(obsB)],true);await write(owner,"FINALIZE","finalize_study",[studyId]);
const study=await owner.readContract({address:contract,functionName:"get_study",args:[studyId],jsonSafeReturn:true});console.log(`FINAL_STUDY=${JSON.stringify(study)}`);if(study.status!=="REPRODUCED"||study.result?.supports!==2||study.submitted_reviewers?.length!==2||study.report_hosts?.length!==2)throw new Error("Live reproduction quorum did not reach the expected state");clearInterval(keeper);
